# Generated by Django 5.2.4 on 2025-07-04 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('banca', models.CharField(max_length=100)),
                ('enunciado', models.TextField()),
                ('alternativas', models.TextField()),
                ('resposta_correta', models.CharField(max_length=1)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_dada', models.CharField(max_length=1)),
                ('acertou', models.BooleanField()),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'questao')},
            },
        ),
    ]
